/* ========================================================================
 * Copyright 2014 disenoPAP2
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 disenoPAP2

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201408112050

*/

package co.edu.uniandes.csw.disenoPAP2.imagen.persistence;

import java.util.List;

import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.Query;

import co.edu.uniandes.csw.disenoPAP2.imagen.logic.dto.ImagenDTO;
import co.edu.uniandes.csw.disenoPAP2.imagen.persistence.api._IImagenPersistence;
import co.edu.uniandes.csw.disenoPAP2.imagen.persistence.converter.ImagenConverter;
import co.edu.uniandes.csw.disenoPAP2.imagen.persistence.entity.ImagenEntity;

public abstract class _ImagenPersistence implements _IImagenPersistence {

  	@PersistenceContext(unitName="disenoPAP2PU")
 
	protected EntityManager entityManager;
	
	public ImagenDTO createImagen(ImagenDTO imagen) {
		ImagenEntity entity=ImagenConverter.persistenceDTO2Entity(imagen);
		entityManager.persist(entity);
		return ImagenConverter.entity2PersistenceDTO(entity);
	}

	@SuppressWarnings("unchecked")
	public List<ImagenDTO> getImagens() {
		Query q = entityManager.createQuery("select u from ImagenEntity u");
		return ImagenConverter.entity2PersistenceDTOList(q.getResultList());
	}

	public ImagenDTO getImagen(Long id) {
		return ImagenConverter.entity2PersistenceDTO(entityManager.find(ImagenEntity.class, id));
	}

	public void deleteImagen(Long id) {
		ImagenEntity entity=entityManager.find(ImagenEntity.class, id);
		entityManager.remove(entity);
	}

	public void updateImagen(ImagenDTO detail) {
		ImagenEntity entity=entityManager.merge(ImagenConverter.persistenceDTO2Entity(detail));
		ImagenConverter.entity2PersistenceDTO(entity);
	}

}